In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('charity_navigator_clean.csv', index_col = 0)

In [3]:
n = 0
for excess_or_deficit in df['excess_or_deficit_for_year']:
    if df.loc[n, 'excess_or_deficit_for_year'] > 0:
        df.loc[n, 'excess_or_deficit'] = 1
        n += 1
    elif df.loc[n, 'excess_or_deficit_for_year'] <= 0:
        df.loc[n, 'excess_or_deficit'] = 0
        n += 1
    else:
        n += 1

In [4]:
comp_leader_df = df[df['compensation_leader_compensation'].isnull() == False]
org_type_dummies = pd.get_dummies(comp_leader_df.org_type)
comp_leader_df = pd.concat([comp_leader_df, org_type_dummies], axis=1, join = 'outer')
comp_leader_df.drop(['charity_name', 'charity_url', 
                     'city', 'cn_advisory', 
                     'state', 'org_type',
                     'org_category', 'compensation_leader_title'], 
                    axis = 1, inplace = True)
comp_leader_df.head()

,accountability_score,administrative_expenses,compensation_leader_compensation,compensation_leader_expense_percent,excess_or_deficit_for_year,financial_score,fundraising_expenses,net_assets,other_revenue,overall_score,...,"Arts, Culture, Humanities",Community Development,Education,Environment,Health,Human Services,Human and Civil Rights,International,Religion,Research and Public Policy
0,89.0,164590.0,53463.0,3.11,349718.0,90.56,111522,1350382,49634.0,89.75,...,0,0,0,0,0,0,1,0,0,0
1,86.0,1001560.0,73500.0,1.47,1175965.0,85.92,54613,14773920,382540.0,85.95,...,0,0,1,0,0,0,0,0,0,0
2,85.0,93957.0,85000.0,0.99,-461502.0,77.65,248833,-770370,0.0,80.96,...,0,0,0,0,0,0,0,1,0,0
3,86.0,346867.0,61220.0,0.78,1872733.0,97.50,384550,11460087,-81726.0,89.94,...,0,0,1,0,0,0,0,0,0,0
4,97.0,135195.0,74244.0,5.41,-103940.0,87.08,87436,723772,32436.0,90.62,...,0,0,0,0,0,0,0,0,1,0

In [5]:
comp_leader_df.describe()

,accountability_score,administrative_expenses,compensation_leader_compensation,compensation_leader_expense_percent,excess_or_deficit_for_year,financial_score,fundraising_expenses,net_assets,other_revenue,overall_score,...,"Arts, Culture, Humanities",Community Development,Education,Environment,Health,Human Services,Human and Civil Rights,International,Religion,Research and Public Policy
count,7290.000000,7.290000e+03,7.290000e+03,7290.000000,7.290000e+03,7290.000000,7.290000e+03,7.290000e+03,7.290000e+03,7290.000000,...,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000,7290.000000
mean,91.338683,1.294414e+06,1.659498e+05,3.543462,9.060532e+05,85.966429,1.070673e+06,3.219307e+07,1.190769e+06,87.178483,...,0.148285,0.096982,0.075583,0.050343,0.100549,0.287929,0.040192,0.068313,0.050206,0.024143
std,8.873393,6.049582e+06,1.298927e+05,2.384256,1.180910e+07,9.940291,6.142220e+06,1.752289e+08,7.803896e+06,7.777421,...,0.355407,0.295954,0.264348,0.218667,0.300751,0.452829,0.196423,0.252299,0.218384,0.153503
min,24.000000,9.440000e+02,1.000000e+00,0.000000,-2.691435e+08,0.000000,1.301000e+03,-1.290334e+07,-1.391081e+07,18.950000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,89.000000,1.945552e+05,9.155775e+04,1.610000,-2.368478e+05,81.180000,1.605952e+05,2.088086e+06,1.116200e+04,83.730000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,93.000000,3.732055e+05,1.311865e+05,3.150000,6.882200e+04,87.500000,3.264685e+05,5.658102e+06,1.145770e+05,88.530000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,97.000000,8.588372e+05,1.977418e+05,5.120000,6.325405e+05,92.500000,7.113882e+05,1.631770e+07,4.977250e+05,92.020000,...,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
max,100.000000,2.569202e+08,2.013535e+06,9.990000,4.531299e+08,100.000000,3.377669e+08,7.551342e+09,3.903250e+08,100.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
from sklearn.cluster import KMeans
from sklearn import metrics

In [7]:
kmeans = KMeans(n_clusters = 2)
kmeans.fit(comp_leader_df.drop('excess_or_deficit', axis = 1))
kmeans.cluster_centers_

array([[ 9.13342488e+01,  1.16559073e+06,  1.65427335e+05,
         3.54721505e+00,  8.43823040e+05,  8.59619239e+01,
         1.00947496e+06,  2.77356584e+07,  1.02064203e+06,
         8.71737009e+01,  1.98015055e+04,  1.27869994e+07,
         1.23216820e+07,  5.75391376e-02,  1.48173579e-01,
         9.69513870e-02,  7.56660258e-02,  5.02609173e-02,
         1.00109860e-01,  2.88244988e-01,  4.02361988e-02,
         6.83878055e-02,  5.02609173e-02,  2.41691843e-02],
       [ 9.53750000e+01,  1.18555475e+08,  6.41498375e+05,
         1.27500000e-01,  5.75510856e+07,  9.00675000e+01,
         5.67765586e+07,  4.08954906e+09,  1.56048525e+08,
         9.15312500e+01, -3.63797881e-12,  6.18068418e+08,
         5.04827543e+08,  6.93889390e-18,  2.50000000e-01,
         1.25000000e-01,  0.00000000e+00,  1.25000000e-01,
         5.00000000e-01,  0.00000000e+00,  0.00000000e+00,
         0.00000000e+00,  0.00000000e+00,  3.46944695e-18]])

In [8]:
print(metrics.classification_report(comp_leader_df['excess_or_deficit'], kmeans.labels_))
print(metrics.confusion_matrix(comp_leader_df['excess_or_deficit'], kmeans.labels_))

             precision    recall  f1-score   support

        0.0       0.43      1.00      0.60      3126
        1.0       0.50      0.00      0.00      4164

avg / total       0.47      0.43      0.26      7290

[[3122    4]
 [4160    4]]