In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('charity_navigator_scraped.csv')

In [3]:
df.head()

,accountability_score,administrative_expenses,charity_name,charity_url,city,cn_advisory,compensation_leader_compensation,compensation_leader_expense_percent,compensation_leader_title,excess_or_deficit_for_year,financial_score,fundraising_expenses,net_assets,organization_type,other_revenue,overall_score,payments_to_affiliates,program_expenses,state,total_contributions
0,89.0,"$164,590",9to5 National Association of Working Women,https://www.charitynavigator.org/index.cfm?bay...,' Milwaukee,NaN,"$53,463",3.11%,Executive Director,"$349,718",90.56,"$111,522","$1,350,382",Human and Civil Rights : Advocacy and Education,"$49,634",89.75,$0,"$1,440,463",WI,"$1,999,023"
1,86.0,"$1,001,560",'Aha Pūnana Leo,https://www.charitynavigator.org/index.cfm?bay...,'\r\n\t\t\tHilo,NaN,"$73,500",1.47%,Executive Director,"$1,175,965",85.92,"$54,613","$14,773,920",Education : Early Childhood Programs and Servi...,"$382,540",85.95,$0,"$3,912,270",HI,"$3,339,358"
2,85.0,"$93,957",AID FOR AIDS International,https://www.charitynavigator.org/index.cfm?bay...,' New York,NaN,"$85,000",0.99%,Executive Director,"$-461,502",77.65,"$248,833","$-770,370",International : Development and Relief Services,$0,80.96,$0,"$8,157,850",NY,"$8,039,138"
3,86.0,"$346,867",Futures in Education,https://www.charitynavigator.org/index.cfm?bay...,'\r\n\t\t\tBrooklyn,NaN,"$61,220",0.78%,Acting Executive Director,"$1,872,733",97.50,"$384,550","$11,460,087","Education : Scholarship and Financial Support ,","$-81,726",89.94,$0,"$7,018,262",NY,"$9,704,138"
4,97.0,"$135,195",Every Generation Ministries,https://www.charitynavigator.org/index.cfm?bay...,' Temecula,NaN,"$74,244",5.41%,President,"$-103,940",87.08,"$87,436","$723,772",Religion : Religious Activities,"$32,436",90.62,$0,"$1,148,407",CA,"$1,234,662"

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8190 entries, 0 to 8189
Data columns (total 20 columns):
accountability_score                   8190 non-null float64
administrative_expenses                8190 non-null object
charity_name                           8187 non-null object
charity_url                            8190 non-null object
city                                   8189 non-null object
cn_advisory                            6 non-null object
compensation_leader_compensation       7763 non-null object
compensation_leader_expense_percent    8190 non-null object
compensation_leader_title              7827 non-null object
excess_or_deficit_for_year             8190 non-null object
financial_score                        8190 non-null float64
fundraising_expenses                   8190 non-null object
net_assets                             8190 non-null object
organization_type                      8190 non-null object
other_revenue                          8190 non-null object
overall_score                          8190 non-null float64
payments_to_affiliates                 8190 non-null object
program_expenses                       8190 non-null object
state                                  8190 non-null object
total_contributions                    8190 non-null object
dtypes: float64(3), object(17)
memory usage: 1.2+ MB